### ISSUE TITLE
Changing dimension of context leads to exception while 'Show Concept Lattice'

### ISSUE THREAD

**Issue by tomhanika** [exot/conexp-clj#3]
Using the GUI I encountered the following problem. 

Minimal example: 
- create a context
- remove any column 
- hit 'Show concept lattice'

leads to:
clojure.lang.ArityException: Wrong number of args (2) passed to: contexts/fn--1656/fn--1658
clojure.lang.AFn.throwArity(AFn.java:429)

**Comment by exot** [comment]
This should be fixed in the dev branch, somehow …
