### ISSUE TITLE
Sorry to bother you

### ISSUE THREAD

**Issue by wiedersehne** [exot/conexp-clj#5]
Dear Mr,I am student from an university in china.
For the research reasons,I found your FCA tool here,and it really a great one to fit my research(it can do the FFCA work).But when I try to download the source code,I just met a 404 ERROR.So I have to download the source code to compile it on Linux.
However because the firewall in china is so strong,so I cant get all the dependencies which are needed in the process of compiling.So I thought to visit your homepage,could you please send me the compiled version of the conexp-clj.
Please do me a favor,thank you very much.my mailbox address is 1127562703@qq.com.

**Comment by exot** [comment]
Hey,

thanks for your interest!  Indeed, the download link was broken, but should work now.  Just try it again and let me know whether it works for you.

Best,

  Daniel

**Comment by wiedersehne** [comment]
Thanks A lot, you really do me a great favor!
